//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNECMV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_UNE_TIPO_CUENTA_BANCA
    {
        public int ID_TIPO_CUENTA_BANCA { get; set; }
        public string DESCRIPCION { get; set; }
    }
}
